# Generated by Django 3.2.8 on 2022-01-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='screws/images')),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subsubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Screw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Screw name')),
                ('group_standard', models.IntegerField(null=True, verbose_name='Standard (group)')),
                ('image', models.ImageField(blank=True, upload_to='screws/images')),
                ('head', models.CharField(max_length=200, verbose_name='Head')),
                ('material', models.CharField(max_length=50, verbose_name='Material')),
                ('coating', models.CharField(max_length=50, verbose_name='Coating')),
                ('length', models.CharField(max_length=50, verbose_name='Length, mm')),
                ('diameter', models.CharField(max_length=50, verbose_name='Diameter, mm')),
                ('carving_type', models.CharField(max_length=100, verbose_name='Carving')),
                ('field_of_use', models.CharField(max_length=100, verbose_name='Usage')),
                ('bit_size', models.CharField(max_length=50, verbose_name='Bit size')),
                ('base', models.CharField(max_length=50, verbose_name='For what base')),
                ('spline', models.CharField(max_length=50, verbose_name='Spline')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('sub_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subgroup')),
                ('subsub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subsubgroup')),
            ],
        ),
    ]
